const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function openModal(id){const m=$('#'+id);if(m){m.classList.add('open');m.setAttribute('aria-hidden','false')}}
function closeModal(id){const m=$('#'+id);if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}}

const caseData={
'TR-2026-00481':{name:'ورثة أحمد عبدالله',type:'ملف تركة',status:'قيد المراجعة',officer:'سارة يوسف',assets:'128,450.000',beneficiaries:4,opened:'12/06/2026',deceased:'أحمد عبدالله حسن',id:'650123456',death:'04/06/2026',court:'المحكمة الكبرى الشرعية',caseNo:'SH-2026-771',subjectHeading:'بيانات المتوفى',subjectNameLabel:'اسم المتوفى',dateLabel:'تاريخ الوفاة',parties:[['محمد أحمد عبدالله','قاصر / وارث','15 سنة','25%'],['مريم أحمد عبدالله','قاصر / وارث','11 سنة','25%'],['يوسف أحمد عبدالله','وارث بالغ','24 سنة','25%'],['فاطمة علي حسن','ولي','—','—']],assetRows:[['عقار سكني','مدينة حمد - عقار 1842','78,000.000','موثق'],['حساب بنكي','بنك البحرين الوطني ••4521','42,300.000','مطابق'],['أسهم','محفظة استثمارية','8,150.000','قيد التقييم']],finance:[['رصيد افتتاحي','128,450.000','12/06/2026'],['إيراد إيجار','450.000','01/08/2026'],['مصروف صيانة','-120.000','03/08/2026']],requests:[['RQ-2026-881','طلب صرف صيانة','1,200.000','قيد المراجعة'],['RQ-2026-742','إضافة مستأجر','—','معتمد']],docs:[['شهادة الوفاة','موثق','12/06/2026'],['الفريضة الشرعية','موثق','14/06/2026'],['سند الملكية','قيد التحقق','16/06/2026']],audit:[['فتح الملف','سارة يوسف','12/06/2026 09:10'],['إضافة قاصر','سارة يوسف','12/06/2026 09:23'],['تحديث أصل عقاري','خالد إبراهيم','07/08/2026 13:05']]},
'MN-2026-01933':{name:'محمد علي حسن',type:'ملف قاصر مرتبط بتركة',status:'فعال',officer:'خالد إبراهيم',assets:'42,850.500',beneficiaries:1,opened:'03/02/2026',deceased:'ملف قاصر مرتبط بتركة TR-2023-00612',id:'110223344',death:'—',court:'—',caseNo:'TR-2023-00612',subjectHeading:'بيانات القاصر',subjectNameLabel:'اسم القاصر',dateLabel:'تاريخ الميلاد'},
'HJ-2026-00204':{name:'علي جاسم محمد',type:'ملف محجور عليه',status:'جديد',officer:'نورة أحمد',assets:'19,600.000',beneficiaries:1,opened:'06/08/2026',deceased:'ملف حجر مستقل',id:'770112233',death:'—',court:'المحكمة الكبرى المدنية',caseNo:'CV-2026-442',subjectHeading:'بيانات المحجور عليه',subjectNameLabel:'اسم المحجور عليه',dateLabel:'تاريخ الميلاد'},
'TR-2025-00876':{name:'ورثة يوسف محمود',type:'ملف تركة',status:'فعال',officer:'مريم صالح',assets:'310,220.750',beneficiaries:6,opened:'19/11/2025',deceased:'يوسف محمود علي',id:'540998877',death:'03/11/2025',court:'المحكمة الكبرى الشرعية',caseNo:'SH-2025-1198',subjectHeading:'بيانات المتوفى',subjectNameLabel:'اسم المتوفى',dateLabel:'تاريخ الوفاة'},
'MN-2024-01104':{name:'فاطمة حسن علي',type:'ملف تحويل وتسوية حسابات الرشد',status:'محول للرشد',officer:'خالد إبراهيم',assets:'61,125.000',beneficiaries:1,opened:'10/05/2024',deceased:'فاطمة حسن علي',id:'060708099',death:'18/05/2008',court:'وزارة العدل',caseNo:'TR-2021-00211',subjectHeading:'بيانات صاحب حساب الرشد',subjectNameLabel:'اسم صاحب الحساب',dateLabel:'تاريخ الميلاد'},
'MI-2026-00041':{name:'سلمان يوسف علي',type:'ملف قاصر مستقل',status:'فعال',officer:'مريم صالح',assets:'27,300.000',beneficiaries:1,opened:'01/08/2026',deceased:'سلمان يوسف علي',id:'120512345',death:'12/05/2012',court:'المحكمة الكبرى الشرعية',caseNo:'MN-IND-2026-041',subjectHeading:'بيانات القاصر',subjectNameLabel:'اسم القاصر',dateLabel:'تاريخ الميلاد'}
};
function rowsTable(headers,rows=[]){return `<div class="table-wrap"><table class="detail-table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="4">لا توجد بيانات تفصيلية في النموذج التجريبي.</td></tr>'}</tbody></table></div>`}
function showCase(id){const d=caseData[id]||caseData['TR-2026-00481'];$('#caseTitle').textContent=`${d.name} — ${id}`;$('#caseMeta').textContent=`${d.type} • الموظف المختص: ${d.officer} • تاريخ فتح الملف: ${d.opened}`;$('#caseSummary').innerHTML=[['الحالة',d.status],['إجمالي الأصول',d.assets+' د.ب'],['عدد المستفيدين',d.beneficiaries],['الموظف المختص',d.officer],['رقم القضية / المرجع',d.caseNo]].map(x=>`<div class="summary-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
$('#detailOverview').innerHTML=`<div class="detail-grid"><div class="detail-card"><h4>البيانات الأساسية للملف</h4><div class="data-list"><div class="data-row"><span>رقم الملف</span><strong>${id}</strong></div><div class="data-row"><span>نوع الملف</span><strong>${d.type}</strong></div><div class="data-row"><span>تاريخ فتح الملف</span><strong>${d.opened}</strong></div><div class="data-row"><span>حالة الملف الحالية</span><strong>${d.status}</strong></div></div></div><div class="detail-card"><h4>${d.subjectHeading||'بيانات صاحب الملف'}</h4><div class="data-list"><div class="data-row"><span>${d.subjectNameLabel||'الاسم الكامل'}</span><strong>${d.deceased}</strong></div><div class="data-row"><span>الرقم الشخصي / رقم الهوية</span><strong>${d.id}</strong></div><div class="data-row"><span>${d.dateLabel||'التاريخ الأساسي'}</span><strong>${d.death}</strong></div><div class="data-row"><span>المحكمة أو الجهة المختصة</span><strong>${d.court}</strong></div></div></div><div class="detail-card"><h4>مسؤولية ومتابعة الملف</h4><div class="data-list"><div class="data-row"><span>الموظف المختص بمتابعة الملف</span><strong>${d.officer}</strong></div><div class="data-row"><span>نسبة اكتمال بيانات الملف</span><strong>92%</strong></div><div class="data-row"><span>طريقة مطابقة البيانات</span><strong>مطابقة يدوية</strong></div><div class="data-row"><span>تاريخ آخر مراجعة للملف</span><strong>07/08/2026</strong></div></div></div></div>`;
$('#detailParties').innerHTML=rowsTable(['الاسم','الصفة','العمر','نسبة الاستحقاق'],d.parties||[['الطرف الرئيسي',d.type,'—','—']]);$('#detailAssets').innerHTML=rowsTable(['نوع الأصل','البيان','القيمة (د.ب)','الحالة'],d.assetRows||[['أصول مالية','رصيد الملف',d.assets,'مسجل']]);$('#detailFinance').innerHTML=rowsTable(['الحركة','المبلغ (د.ب)','التاريخ'],d.finance||[['الرصيد الحالي',d.assets,d.opened]]);$('#detailRequests').innerHTML=rowsTable(['رقم الطلب','النوع','المبلغ','الحالة'],d.requests||[]);$('#detailDocs').innerHTML=rowsTable(['المستند','الحالة','تاريخ الإضافة'],d.docs||[['مستند أساسي','موجود',d.opened]]);$('#detailAudit').innerHTML=rowsTable(['الإجراء','المستخدم','الوقت'],d.audit||[['فتح الملف',d.officer,d.opened]]);openModal('caseModal')}

function initTabs(root=document){$$('.tab-btn',root).forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',()=>{const group=btn.closest('[data-tabs]');if(!group)return;$$('.tab-btn',group).forEach(b=>b.classList.remove('active'));$$('.tab-panel',group).forEach(p=>p.classList.remove('active'));btn.classList.add('active');$('#'+btn.dataset.tab,group)?.classList.add('active')})})}
function initWizard(){
  let step=0;
  const panels=$$('.wizard-panel'),steps=$$('.wizard-step'),prev=$('#wizardPrev'),next=$('#wizardNext'),create=$('#wizardCreate'),fileType=$('#fileType');
  const configs={
    'estate':{label:'ملف تركة',prefix:'TR',title:'فتح ملف تركة جديد',section:'بيانات المتوفى والتركة',help:'أدخل بيانات المتوفى والمرجع القضائي الذي ستُبنى عليه التركة.',idLabel:'الرقم الشخصي للمتوفى *',nameLabel:'اسم المتوفى بالكامل *',dateLabel:'تاريخ الوفاة *',certificateLabel:'رقم شهادة الوفاة',referenceLabel:'رقم قضية التركة / حصر الإرث',workflow:'استكمال بيانات التركة ← مطابقة ← مراجعة ← تفعيل',notice:'بعد إنشاء ملف التركة يمكن إضافة الورثة والقاصرين وربط كل مستفيد بأصوله وحصته ومستنداته.'},
    'minor-estate':{label:'ملف قاصر مرتبط بتركة',prefix:'MN',title:'فتح ملف قاصر مرتبط بتركة',section:'بيانات القاصر والملف الأم',help:'أدخل بيانات القاصر وحدد مرجع التركة التي يتبع لها.',idLabel:'الرقم الشخصي للقاصر *',nameLabel:'اسم القاصر بالكامل *',dateLabel:'تاريخ ميلاد القاصر *',certificateLabel:'رقم شهادة الميلاد',referenceLabel:'رقم ملف التركة المرتبط *',workflow:'ربط بالتركة ← التحقق من الولي ← تحديد الحصة ← تفعيل',notice:'بعد الإنشاء سيبقى ملف القاصر مرتبطًا بملف التركة مع إمكانية متابعة حصته وحساباته وأصوله بصورة مستقلة.'},
    'minor-independent':{label:'ملف قاصر مستقل',prefix:'MI',title:'فتح ملف قاصر مستقل',section:'بيانات القاصر وسبب فتح الملف المستقل',help:'يستخدم هذا النوع عندما تتم إدارة أموال القاصر في ملف مستقل غير تابع مباشرة لملف تركة.',idLabel:'الرقم الشخصي للقاصر *',nameLabel:'اسم القاصر بالكامل *',dateLabel:'تاريخ ميلاد القاصر *',certificateLabel:'رقم شهادة الميلاد / المستند التعريفي',referenceLabel:'رقم القرار أو المرجع الرسمي',workflow:'التحقق من الولاية ← تسجيل الأموال ← مراجعة ← تفعيل',notice:'بعد الإنشاء يمكن إدارة أموال القاصر وأصوله وحساباته وطلباته داخل هذا الملف المستقل.'},
    'interdicted':{label:'ملف محجور عليه',prefix:'HJ',title:'فتح ملف محجور عليه',section:'بيانات المحجور عليه وقرار الحجر',help:'أدخل بيانات الشخص وقرار الحجر أو المرجع القضائي وتفاصيل القيم المسؤول عنه.',idLabel:'الرقم الشخصي للمحجور عليه *',nameLabel:'اسم المحجور عليه بالكامل *',dateLabel:'تاريخ الميلاد *',certificateLabel:'رقم قرار / حكم الحجر',referenceLabel:'رقم القضية أو القرار القضائي *',workflow:'التحقق من قرار الحجر ← تسجيل القيم ← تسجيل الأموال ← تفعيل',notice:'بعد الإنشاء يمكن ربط القيم والأصول والحسابات والطلبات المالية بملف المحجور عليه.'},
    'adulthood':{label:'ملف تحويل وتسوية حسابات الرشد',prefix:'AD',title:'فتح ملف تحويل وتسوية حسابات الرشد',section:'بيانات المستفيد وملف القاصر السابق',help:'يستخدم لتوثيق انتقال ملف القاصر إلى مرحلة الرشد وتسوية الأموال والحسابات قبل التسليم.',idLabel:'الرقم الشخصي للمستفيد *',nameLabel:'اسم المستفيد بالكامل *',dateLabel:'تاريخ الميلاد *',certificateLabel:'رقم مستند إثبات بلوغ الرشد',referenceLabel:'رقم ملف القاصر السابق *',workflow:'التحقق من بلوغ الرشد ← تسوية الحسابات ← مراجعة ← تسليم / إغلاق',notice:'بعد الإنشاء تتم مراجعة أرصدة وأصول ملف القاصر السابق وتوثيق إجراءات التسوية والتسليم.'}
  };
  function cfg(){return configs[fileType?.value]||null}
  function paint(){panels.forEach((p,i)=>p.classList.toggle('active',i===step));steps.forEach((s,i)=>{s.classList.toggle('active',i===step);s.classList.toggle('done',i<step)});prev.disabled=step===0;next.classList.toggle('hidden',step===panels.length-1);create.classList.toggle('hidden',step!==panels.length-1)}
  function updateTypeUI(){const c=cfg();$('#wizardEyebrow').textContent=c?c.label:'فتح ملف جديد';$('#wizardTitle').textContent=c?c.title:'معالج إنشاء ملف جديد';$('#primarySectionTitle').textContent=c?c.section:'المعلومات الأساسية للملف';$('#primarySectionHelp').textContent=c?c.help:'اختر نوع الملف أولاً، ثم أدخل البيانات الأساسية المطلوبة لفتحه.';$('#primaryIdLabel').textContent=c?c.idLabel:'الرقم الشخصي / رقم الهوية *';$('#primaryNameLabel').textContent=c?c.nameLabel:'اسم صاحب الملف بالكامل *';$('#primaryDateLabel').textContent=c?c.dateLabel:'التاريخ الأساسي *';$('#certificateLabel').textContent=c?c.certificateLabel:'رقم المستند الأساسي';$('#caseReferenceLabel').textContent=c?c.referenceLabel:'رقم القضية / المرجع الرسمي';$('#reviewFileType').textContent=c?c.label:'لم يتم الاختيار بعد';$('#reviewWorkflow').textContent=c?c.workflow:'استكمال البيانات ← مطابقة ← مراجعة ← تفعيل';$('#reviewNotice').textContent=c?c.notice:'بعد إنشاء الملف يمكن فتح «تفاصيل الملف» مباشرة لاستكمال جميع البيانات المرتبطة به.';create.textContent=c?`إنشاء ${c.label}`:'إنشاء الملف'}
  function validate(){const inputs=$$('input[required],select[required]',panels[step]);for(const i of inputs){if(!i.value){i.focus();toast(i===fileType?'يرجى اختيار نوع الملف المراد فتحه':'يرجى استكمال جميع الحقول الإلزامية في هذه الخطوة');return false}}return true}
  next?.addEventListener('click',()=>{if(validate()&&step<panels.length-1){step++;paint()}});
  prev?.addEventListener('click',()=>{if(step>0){step--;paint()}});
  steps.forEach((s,i)=>s.addEventListener('click',()=>{if(i<=step||validate()){step=i;paint()}}));
  fileType?.addEventListener('change',updateTypeUI);
  $('#addParty')?.addEventListener('click',()=>{$('#partyList').innerHTML+=`<div><strong>طرف مرتبط إضافي</strong><span>تمت إضافة سجل تجريبي؛ يمكن استكمال صفته وبياناته داخل النظام الفعلي.</span></div>`;toast('تمت إضافة طرف مرتبط جديد')});
  $$('[data-asset]').forEach(b=>b.addEventListener('click',()=>{$('#assetList').innerHTML+=`<div><strong>${b.dataset.asset}</strong><span>تمت إضافة الأصل إلى الملف ويحتاج استكمال بيانات الملكية والقيمة.</span></div>`;toast(`تمت إضافة أصل من نوع: ${b.dataset.asset}`)}));
  create?.addEventListener('click',()=>{const c=cfg();if(!c)return toast('يرجى اختيار نوع الملف');closeModal('wizardModal');const demoNo=`${c.prefix}-2026-00502`;toast(`تم إنشاء ${c.label} برقم تجريبي ${demoNo}`);setTimeout(()=>showCase(c.prefix==='TR'?'TR-2026-00481':c.prefix==='HJ'?'HJ-2026-00204':c.prefix==='MI'?'MI-2026-00041':c.prefix==='AD'?'MN-2024-01104':'MN-2026-01933'),500)});
  $('#newFileBtn')?.addEventListener('click',()=>{step=0;$('#caseWizard')?.reset();updateTypeUI();paint();openModal('wizardModal')});
  updateTypeUI();paint()
}
function initShell(){const sidebar=$('#sidebar'),main=$('#main'),toggle=$('#navToggle');toggle?.addEventListener('click',()=>{if(window.innerWidth<=820)sidebar.classList.toggle('mobile-open');else{sidebar.classList.toggle('collapsed');main.classList.toggle('expanded')}});$$('.nav-parent').forEach(btn=>btn.addEventListener('click',()=>btn.closest('.nav-group')?.classList.toggle('open')));$$('.nav-item').forEach(item=>item.addEventListener('click',()=>{if(item.tagName==='A')return;$$('.nav-item').forEach(i=>i.classList.remove('active'));item.classList.add('active');const title=item.dataset.title||item.textContent.trim();$('#currentCrumb').textContent=title;toast(`تم الانتقال إلى: ${title}`);if(window.innerWidth<=820)sidebar?.classList.remove('mobile-open')}));initTabs();$('#notificationsBtn')?.addEventListener('click',()=>toast('لديك 6 تنبيهات تشغيلية تحتاج إلى المراجعة'));$('#exportBtn')?.addEventListener('click',()=>toast('تم تجهيز ملف تجريبي لتصدير قائمة الملفات الحالية'));const filterCases=()=>{const q=$('#searchInput')?.value.trim()||'',type=$('#caseTypeFilter')?.value||'';$$('#casesTable tbody tr').forEach(row=>{const matchesText=!q||row.textContent.includes(q),matchesType=!type||row.children[1]?.textContent.trim()===type;row.style.display=matchesText&&matchesType?'':'none'})};$('#searchInput')?.addEventListener('input',filterCases);$('#caseTypeFilter')?.addEventListener('change',filterCases);$$('.view-case').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();showCase(b.closest('tr').dataset.case)}));$$('#casesTable tbody tr[data-case]').forEach(r=>{r.classList.add('clickable-row');r.addEventListener('dblclick',()=>showCase(r.dataset.case))});$$('.modal-close').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));$$('.modal-shell').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));initWizard()}
function initLogin(){$('#ekeyBtn')?.addEventListener('click',()=>{toast('محاكاة الانتقال إلى eKey 2.0');setTimeout(()=>location.href='index.html',700)});$('#staffLogin')?.addEventListener('submit',e=>{e.preventDefault();const u=$('#username')?.value.trim(),p=$('#password')?.value.trim();if(!u||!p)return toast('يرجى إدخال اسم المستخدم وكلمة المرور');toast('تم تسجيل الدخول التجريبي بنجاح');setTimeout(()=>location.href='index.html',650)})}
document.addEventListener('DOMContentLoaded',()=>{initShell();initLogin()});
