const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const STORAGE_KEY='mof_minors_prototype_cases_v3';
const typeMeta={
  estate:{label:'تركة',prefix:'TR',icon:'⚖',help:'ملف التركة: سيتم إنشاء ملف رئيسي ويمكن ربط سجلات القاصرين المستفيدين به.'},
  minor:{label:'قاصر',prefix:'MN',icon:'◉',help:'ملف أموال القاصر: ملف مستقل لإدارة أموال وأصول القاصر مع الولي أو الوصي.'},
  interdicted:{label:'محجور عليه',prefix:'HJ',icon:'§',help:'ملف المحجور عليه: ملف مستقل لإدارة المال بموجب قرار قضائي وتحت إشراف القيم.'}
};
const statusMeta={new:{label:'جديد',cls:'new'},review:{label:'قيد المراجعة',cls:'review'},active:{label:'فعال',cls:'active'},maturity:{label:'تحويل للرشد',cls:'maturity'},closed:{label:'مغلق',cls:'closed'}};
const officers=['سارة يوسف','خالد إبراهيم','نورة أحمد','مريم صالح','أحمد سلمان'];
const seedCases=[
{id:'TR-2026-00481',type:'estate',name:'ورثة أحمد عبدالله حسن',subject:'أحمد عبدالله حسن',personalId:'650123456',status:'review',officer:'سارة يوسف',assetsTotal:128450,completion:92,lastAction:'اليوم 10:42',opened:'12/06/2026',priority:'high',overdue:true,missing:false,reference:'SH-2026-771',court:'المحكمة الكبرى الشرعية',primary:{'اسم المتوفى':'أحمد عبدالله حسن','الرقم الشخصي':'650123456','تاريخ الوفاة':'04/06/2026','رقم الفريضة / القضية':'SH-2026-771','المحكمة':'المحكمة الكبرى الشرعية'},parties:[{name:'محمد أحمد عبدالله',role:'قاصر / وارث',id:'110001122',extra:'25%'},{name:'مريم أحمد عبدالله',role:'قاصر / وارث',id:'120003344',extra:'25%'},{name:'يوسف أحمد عبدالله',role:'وارث بالغ',id:'990008877',extra:'25%'},{name:'فاطمة علي حسن',role:'ولي',id:'720112233',extra:'—'}],assets:[{type:'عقار',description:'مدينة حمد - عقار 1842',value:78000,status:'موثق',reference:'1842'},{type:'حساب بنكي',description:'بنك البحرين الوطني ••4521',value:42300,status:'مطابق',reference:'4521'},{type:'استثمار / أسهم',description:'محفظة استثمارية',value:8150,status:'قيد التقييم',reference:'INV-88'}],docs:[{name:'شهادة الوفاة',status:'موثق'},{name:'الفريضة الشرعية',status:'موثق'},{name:'سند الملكية',status:'قيد التحقق'}],finance:[{label:'رصيد افتتاحي',amount:128450,date:'12/06/2026'},{label:'إيراد إيجار',amount:450,date:'01/08/2026'},{label:'مصروف صيانة',amount:-120,date:'03/08/2026'}],requests:[{id:'RQ-2026-881',type:'طلب صرف صيانة',amount:1200,status:'قيد المراجعة'},{id:'RQ-2026-742',type:'إضافة مستأجر',amount:null,status:'معتمد'}],audit:[{action:'فتح الملف',user:'سارة يوسف',date:'12/06/2026 09:10'},{action:'إضافة قاصر',user:'سارة يوسف',date:'12/06/2026 09:23'},{action:'تحديث أصل عقاري',user:'خالد إبراهيم',date:'07/08/2026 13:05'}],related:[{id:'MN-2026-01933',label:'محمد أحمد عبدالله - قاصر'}]},
{id:'MN-2026-01933',type:'minor',name:'محمد علي حسن',subject:'محمد علي حسن',personalId:'110223344',status:'active',officer:'خالد إبراهيم',assetsTotal:42850.5,completion:98,lastAction:'أمس 14:10',opened:'03/02/2026',priority:'normal',overdue:false,missing:false,reference:'TR-2023-00612',court:'—',primary:{'اسم القاصر':'محمد علي حسن','الرقم الشخصي':'110223344','تاريخ الميلاد':'17/09/2010','مصدر المال':'حصة تركة + أموال خاصة','الملف المرتبط':'TR-2023-00612'},parties:[{name:'محمد علي حسن',role:'القاصر',id:'110223344',extra:'15 سنة'},{name:'علي حسن يوسف',role:'ولي',id:'790554433',extra:'فعال'}],assets:[{type:'حساب بنكي',description:'حساب أمانات القاصر',value:36200.5,status:'مطابق',reference:'AC-9901'},{type:'استثمار / أسهم',description:'محفظة استثمار منخفضة المخاطر',value:6650,status:'موثق',reference:'INV-210'}],docs:[{name:'شهادة الميلاد',status:'موثق'},{name:'قرار الولاية',status:'موثق'}],finance:[{label:'رصيد مرحل',amount:42000,date:'03/02/2026'},{label:'عائد استثمار',amount:850.5,date:'31/07/2026'}],requests:[{id:'RQ-2026-910',type:'طلب مصروف تعليمي',amount:400,status:'معتمد'}],audit:[{action:'فتح الملف',user:'خالد إبراهيم',date:'03/02/2026 10:05'},{action:'مطابقة الحساب',user:'خالد إبراهيم',date:'19/07/2026 09:30'}],related:[{id:'TR-2023-00612',label:'ملف التركة المرتبط'}]},
{id:'HJ-2026-00204',type:'interdicted',name:'علي جاسم محمد',subject:'علي جاسم محمد',personalId:'770112233',status:'new',officer:'نورة أحمد',assetsTotal:19600,completion:64,lastAction:'اليوم 09:15',opened:'06/08/2026',priority:'urgent',overdue:false,missing:true,reference:'CV-2026-442',court:'المحكمة الكبرى المدنية',primary:{'اسم المحجور عليه':'علي جاسم محمد','الرقم الشخصي':'770112233','رقم قرار الحجر':'CV-2026-442','تاريخ القرار':'05/08/2026','المحكمة':'المحكمة الكبرى المدنية'},parties:[{name:'علي جاسم محمد',role:'المحجور عليه',id:'770112233',extra:'—'},{name:'جاسم محمد علي',role:'قيم',id:'680112299',extra:'مكلف'}],assets:[{type:'حساب بنكي',description:'حساب جاري',value:14600,status:'قيد التحقق',reference:'AC-320'},{type:'مركبة',description:'مركبة خاصة',value:5000,status:'قيد التقييم',reference:'REG-211'}],docs:[{name:'طلب الحجر',status:'موثق'},{name:'قرار المحكمة',status:'ناقص'}],finance:[{label:'رصيد أولي تقديري',amount:19600,date:'06/08/2026'}],requests:[],audit:[{action:'فتح الملف',user:'نورة أحمد',date:'06/08/2026 09:15'}],related:[]},
{id:'TR-2025-00876',type:'estate',name:'ورثة يوسف محمود علي',subject:'يوسف محمود علي',personalId:'540998877',status:'active',officer:'مريم صالح',assetsTotal:310220.75,completion:100,lastAction:'07/08/2026',opened:'19/11/2025',priority:'normal',overdue:false,missing:false,reference:'SH-2025-1198',court:'المحكمة الكبرى الشرعية',primary:{'اسم المتوفى':'يوسف محمود علي','الرقم الشخصي':'540998877','تاريخ الوفاة':'03/11/2025','رقم الفريضة / القضية':'SH-2025-1198','المحكمة':'المحكمة الكبرى الشرعية'},parties:[{name:'أحمد يوسف محمود',role:'وارث بالغ',id:'900112255',extra:'33.33%'},{name:'ليلى يوسف محمود',role:'قاصر / وارث',id:'120888777',extra:'33.33%'},{name:'نور يوسف محمود',role:'قاصر / وارث',id:'140232211',extra:'33.33%'}],assets:[{type:'عقار',description:'مبنى استثماري - المنامة',value:260000,status:'موثق',reference:'PROP-760'},{type:'حساب بنكي',description:'حساب مصرفي',value:50220.75,status:'مطابق',reference:'AC-887'}],docs:[{name:'شهادة الوفاة',status:'موثق'},{name:'الفريضة الشرعية',status:'موثق'}],finance:[{label:'رصيد افتتاحي',amount:310220.75,date:'19/11/2025'},{label:'إيراد إيجار',amount:2850,date:'01/08/2026'}],requests:[],audit:[{action:'اعتماد الملف',user:'مريم صالح',date:'21/11/2025 12:40'}],related:[]},
{id:'MN-2024-01104',type:'minor',name:'فاطمة حسن علي',subject:'فاطمة حسن علي',personalId:'060708099',status:'maturity',officer:'خالد إبراهيم',assetsTotal:61125,completion:100,lastAction:'05/08/2026',opened:'10/05/2024',priority:'high',overdue:false,missing:false,reference:'TR-2021-00211',court:'—',primary:{'اسم القاصر':'فاطمة حسن علي','الرقم الشخصي':'060708099','تاريخ الميلاد':'08/08/2008','مصدر المال':'تركة','الملف المرتبط':'TR-2021-00211'},parties:[{name:'فاطمة حسن علي',role:'صاحبة المال',id:'060708099',extra:'مسار الرشد'},{name:'حسن علي محمد',role:'ولي سابق',id:'760443322',extra:'—'}],assets:[{type:'حساب بنكي',description:'رصيد جاهز للتسليم',value:61125,status:'مطابق',reference:'AC-611'}],docs:[{name:'إفادة الرشد',status:'موثق'},{name:'كشف الحساب النهائي',status:'موثق'}],finance:[{label:'الرصيد النهائي',amount:61125,date:'05/08/2026'}],requests:[{id:'RQ-2026-998',type:'تحويل حسابات الرشد',amount:61125,status:'قيد الاعتماد'}],audit:[{action:'بدء إجراءات الرشد',user:'خالد إبراهيم',date:'05/08/2026 11:20'}],related:[{id:'TR-2021-00211',label:'ملف التركة الأصلي'}]},
{id:'HJ-2025-00118',type:'interdicted',name:'سلمان إبراهيم عبدالله',subject:'سلمان إبراهيم عبدالله',personalId:'680887766',status:'active',officer:'أحمد سلمان',assetsTotal:87400,completion:88,lastAction:'06/08/2026',opened:'14/09/2025',priority:'normal',overdue:true,missing:false,reference:'CV-2025-882',court:'المحكمة الكبرى المدنية',primary:{'اسم المحجور عليه':'سلمان إبراهيم عبدالله','الرقم الشخصي':'680887766','رقم قرار الحجر':'CV-2025-882','تاريخ القرار':'10/09/2025','المحكمة':'المحكمة الكبرى المدنية'},parties:[{name:'سلمان إبراهيم عبدالله',role:'المحجور عليه',id:'680887766',extra:'—'},{name:'إبراهيم سلمان علي',role:'قيم',id:'700221133',extra:'فعال'}],assets:[{type:'عقار',description:'شقة سكنية - المحرق',value:72000,status:'موثق',reference:'PROP-302'},{type:'حساب بنكي',description:'رصيد تشغيلي',value:15400,status:'مطابق',reference:'AC-118'}],docs:[{name:'قرار المحكمة',status:'موثق'},{name:'تقرير الأصول',status:'موثق'}],finance:[{label:'رصيد افتتاحي',amount:87400,date:'14/09/2025'},{label:'مصروف خدمات',amount:-280,date:'01/08/2026'}],requests:[{id:'RQ-2026-712',type:'مصروف خدمات',amount:280,status:'قيد المراجعة'}],audit:[{action:'فتح الملف',user:'أحمد سلمان',date:'14/09/2025 09:00'}],related:[]}
];
let cases=[];let currentCaseId=null;let filters={type:'all',status:'all',officer:'all',q:'',quick:null};
const wizardState={step:0,type:'estate',parties:[],assets:[],assetType:null};

function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
function openModal(id){const m=$('#'+id);if(m){m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}}
function closeModal(id){const m=$('#'+id);if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true');if(!$('.modal-shell.open'))document.body.style.overflow=''}}
function money(v){return new Intl.NumberFormat('en-US',{minimumFractionDigits:3,maximumFractionDigits:3}).format(Number(v||0))+' د.ب'}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function nowStamp(){return new Date().toLocaleString('ar-BH',{dateStyle:'short',timeStyle:'short'})}
function loadCases(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));cases=Array.isArray(saved)&&saved.length?saved:structuredClone(seedCases)}catch{cases=structuredClone(seedCases)}}
function saveCases(){localStorage.setItem(STORAGE_KEY,JSON.stringify(cases))}

function updateOfficerFilter(){const sel=$('#officerFilter');if(!sel)return;const val=sel.value;const names=[...new Set(cases.map(c=>c.officer))].sort();sel.innerHTML='<option value="all">كل الموظفين</option>'+names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');if(names.includes(val))sel.value=val}
function calcStats(){const count=s=>cases.filter(c=>c.status===s).length;$('#kpiNew').textContent=count('new');$('#kpiReview').textContent=count('review');$('#kpiActive').textContent=count('active');$('#kpiMaturity').textContent=count('maturity');$('#kpiAssets').textContent=money(cases.reduce((a,c)=>a+Number(c.assetsTotal||0),0));
  $('#navAllCount').textContent=cases.length;$('#navEstateCount').textContent=cases.filter(c=>c.type==='estate').length;$('#navMinorCount').textContent=cases.filter(c=>c.type==='minor').length;$('#navInterdictedCount').textContent=cases.filter(c=>c.type==='interdicted').length;
  $('#overdueCount').textContent=`${cases.filter(c=>c.overdue).length} معاملات متأخرة`;$('#missingCount').textContent=`${cases.filter(c=>c.missing||c.completion<75).length} ملفات ناقصة`;$('#maturityCount').textContent=`${count('maturity')} تحويلات للرشد`;
  const dist=$('#typeDistribution');if(dist){const total=Math.max(cases.length,1);dist.innerHTML=['estate','minor','interdicted'].map(t=>{const n=cases.filter(c=>c.type===t).length;return `<div class="distribution-row"><strong>${typeMeta[t].label}</strong><div class="bar-track"><div class="bar-fill ${t}" style="width:${Math.round(n/total*100)}%"></div></div><div class="distribution-value">${n}</div></div>`}).join('')}
}
function filteredCases(){return cases.filter(c=>{if(filters.type!=='all'&&c.type!==filters.type)return false;if(filters.status!=='all'&&c.status!==filters.status)return false;if(filters.officer!=='all'&&c.officer!==filters.officer)return false;if(filters.quick==='overdue'&&!c.overdue)return false;if(filters.quick==='missing'&&!(c.missing||c.completion<75))return false;if(filters.quick==='maturity'&&c.status!=='maturity')return false;const q=filters.q.trim().toLowerCase();if(q&&!`${c.id} ${c.name} ${c.subject} ${c.personalId} ${c.officer} ${c.reference}`.toLowerCase().includes(q))return false;return true})}
function renderCases(){const rows=filteredCases();$('#resultCount').textContent=rows.length;$('#emptyState').classList.toggle('hidden',rows.length>0);$('#casesBody').innerHTML=rows.map(c=>`<tr data-case="${esc(c.id)}"><td><span class="file-id">${esc(c.id)}</span></td><td><span class="type-pill ${c.type}">${typeMeta[c.type].label}</span></td><td class="file-name"><strong>${esc(c.name)}</strong><small>${esc(c.personalId||'')}</small></td><td><span class="status ${statusMeta[c.status].cls}">${statusMeta[c.status].label}</span></td><td>${esc(c.officer)}</td><td class="amount">${money(c.assetsTotal)}</td><td><div class="completion"><div class="mini-progress"><i style="width:${Number(c.completion)||0}%"></i></div><span>${c.completion}%</span></div></td><td>${esc(c.lastAction)}</td><td><button class="row-menu" title="فتح الملف">⋯</button></td></tr>`).join('');
  $$('#casesBody tr').forEach(r=>r.addEventListener('click',()=>showCase(r.dataset.case)));
}
function updateFiltersUI(){ $$('#typeChips .chip').forEach(b=>b.classList.toggle('active',b.dataset.type===filters.type));$('#statusFilter').value=filters.status;$('#officerFilter').value=filters.officer;$('#searchInput').value=filters.q }
function applyView(view,title){$('#workspacePlaceholder').classList.add('hidden');$('#filesRegion').classList.remove('hidden');$('#dashboardSection').classList.toggle('hidden',view!=='dashboard');filters.quick=null;
  if(view==='dashboard'||view==='all'){filters.type='all';filters.status='all'}
  else if(['estate','minor','interdicted'].includes(view)){filters.type=view;filters.status='all'}
  else if(view==='review'||view==='approval'){filters.type='all';filters.status='review'}
  else if(view==='overdue'){filters.type='all';filters.status='all';filters.quick='overdue'}
  else{showWorkspace(view,title);return}
  const titles={dashboard:['لوحة التحكم التشغيلية','إدارة موحدة للتركات، أموال القاصرين، والمحجور عليهم مع متابعة الأصول والموافقات.'],all:['جميع الملفات','السجل الموحد لكافة أنواع الملفات.'],estate:['ملفات التركات','متابعة التركات والورثة والقاصرين والأصول المرتبطة.'],minor:['ملفات أموال القاصرين','ملفات القاصرين المستقلة أو المرتبطة بملفات أخرى.'],interdicted:['ملفات المحجور عليهم','ملفات إدارة الأموال بموجب قرارات الحجر.'],review:['صندوق المراجعة','الملفات والمعاملات قيد المراجعة.'],approval:['طلبات الاعتماد','الملفات التي تتطلب قرار اعتماد.'],overdue:['المعاملات المتأخرة','ملفات ومعاملات تجاوزت مدة المعالجة المستهدفة.']};const [h,p]=titles[view]||[title,''];$('#pageTitle').textContent=h;$('#pageSubtitle').textContent=p;$('#tableTitle').textContent=h==='لوحة التحكم التشغيلية'?'مركز الملفات':h;$('#tableSubtitle').textContent=p;updateFiltersUI();renderCases()}
function showWorkspace(view,title){$('#dashboardSection').classList.add('hidden');$('#filesRegion').classList.add('hidden');$('#workspacePlaceholder').classList.remove('hidden');$('#pageTitle').textContent=title;$('#pageSubtitle').textContent='واجهة تشغيلية تجريبية ضمن النموذج الأولي المتقدم.';$('#placeholderTitle').textContent=title;const map={assets:['سجل موحد للأصول','بطاقات العقارات والحسابات والاستثمارات','حالات التقييم والمطابقة'],properties:['العقارات','الوحدات والعقود','التحصيلات والمتأخرات'],collections:['تحصيلات الشهر','الإيرادات المتوقعة','المطابقة اليدوية'],ledger:['شجرة الحسابات','أرصدة الملفات','مراكز التكلفة'],journals:['قيود يومية','قيود بانتظار الاعتماد','سجل القيود المرحلة'],reconciliation:['مطابقة الحسابات','فروقات تحتاج معالجة','آخر مطابقة'],reports:['التقرير التشغيلي','أداء الموظفين','أعمار المعاملات'],'financial-reports':['ملخص الأرصدة','الإيرادات والمصروفات','حركة الأصول'],'control-reports':['سجل التدقيق','فصل الصلاحيات','الاستثناءات'],users:['المستخدمون','الأدوار الوظيفية','مصفوفة الصلاحيات'],settings:['أنواع الملفات والطلبات','مسارات الموافقات','إعدادات النظام']};const items=map[view]||['منطقة العمل','مكون APEX Region','سيتم ربطه بالبيانات لاحقاً'];$('#placeholderBody').innerHTML=`<div class="placeholder-grid">${items.map((x,i)=>`<div class="placeholder-card"><strong>${x}</strong><p>${i===0?'ملخص تجريبي قابل للتحويل إلى APEX Cards / Interactive Report.':'مكان مخصص للبيانات والإجراءات المرتبطة بهذه الوحدة.'}</p></div>`).join('')}</div>`}

function rowsTable(headers,rows,formatters=[]){return `<div class="table-wrap"><table class="detail-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map((c,i)=>`<td>${formatters[i]?formatters[i](c):esc(c??'—')}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">لا توجد بيانات مسجلة.</td></tr>`}</tbody></table></div>`}
function showCase(id){const c=cases.find(x=>x.id===id);if(!c)return;currentCaseId=id;$('#caseTypeBadge').textContent=typeMeta[c.type].icon+'\n'+typeMeta[c.type].label;$('#caseIdLabel').textContent=c.id;$('#caseTitle').textContent=c.name;$('#caseMeta').textContent=`${typeMeta[c.type].label} • الموظف المختص: ${c.officer} • تاريخ الفتح: ${c.opened}`;
  const summaries=[['الحالة',statusMeta[c.status].label],['إجمالي الأصول',money(c.assetsTotal)],['عدد الأطراف',c.parties?.length||0],['الموظف المختص',c.officer],['المرجع',c.reference||'—']];$('#caseSummary').innerHTML=summaries.map(x=>`<div class="summary-item"><span>${x[0]}</span><strong>${esc(x[1])}</strong></div>`).join('');
  $('#caseCompletion').textContent=c.completion+'%';$('.progress-circle').style.setProperty('--progress',c.completion+'%');$('#quickFacts').innerHTML=`<div class="quick-fact"><span>الرقم الشخصي</span><strong>${esc(c.personalId||'—')}</strong></div><div class="quick-fact"><span>الأولوية</span><strong>${c.priority==='urgent'?'عاجلة':c.priority==='high'?'عالية':'عادية'}</strong></div><div class="quick-fact"><span>المحكمة</span><strong>${esc(c.court||'—')}</strong></div><div class="quick-fact"><span>آخر إجراء</span><strong>${esc(c.lastAction)}</strong></div>`;
  $('#relatedCases').innerHTML=(c.related?.length?c.related:[{id:'',label:'لا توجد ملفات مرتبطة'}]).map(r=>`<div class="related-case" data-related="${esc(r.id)}"><strong>${esc(r.id||'—')}</strong><small>${esc(r.label)}</small></div>`).join('');$$('[data-related]').forEach(r=>{if(r.dataset.related)r.addEventListener('click',()=>showCase(r.dataset.related))});
  const primaryRows=Object.entries(c.primary||{}).map(([k,v])=>`<div class="data-row"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('');const timeline=(c.audit||[]).slice().reverse().slice(0,5).map(a=>`<div class="timeline-item"><span class="timeline-dot"></span><div><strong>${esc(a.action)}</strong><small>${esc(a.user)} • ${esc(a.date)}</small></div></div>`).join('');
  $('#detailOverview').innerHTML=`<div class="overview-grid"><div class="overview-stack"><div class="detail-card"><h4>المعلومات الرئيسية</h4><div class="data-list">${primaryRows}<div class="data-row"><span>حالة الملف</span><strong>${statusMeta[c.status].label}</strong></div></div></div><div class="detail-card"><h4>إدارة الملف</h4><div class="data-list"><div class="data-row"><span>الموظف المختص</span><strong>${esc(c.officer)}</strong></div><div class="data-row"><span>تاريخ الفتح</span><strong>${esc(c.opened)}</strong></div><div class="data-row"><span>اكتمال البيانات</span><strong>${c.completion}%</strong></div><div class="data-row"><span>المطابقة المالية</span><strong>يدوية</strong></div></div></div></div><div class="overview-stack"><div class="detail-card"><h4>آخر النشاطات</h4><div class="timeline">${timeline||'<p>لا توجد نشاطات.</p>'}</div></div><div class="detail-card"><h4>مؤشرات الملف</h4><div class="data-list"><div class="data-row"><span>عدد الأصول</span><strong>${c.assets?.length||0}</strong></div><div class="data-row"><span>الطلبات المفتوحة</span><strong>${(c.requests||[]).filter(r=>!['معتمد','مرفوض'].includes(r.status)).length}</strong></div><div class="data-row"><span>المستندات</span><strong>${c.docs?.length||0}</strong></div></div></div></div></div>`;
  $('#detailParties').innerHTML=`<div class="detail-toolbar"><h3>الأطراف المرتبطة بالملف</h3><button class="btn btn-secondary" id="detailAddParty">＋ إضافة طرف</button></div>`+rowsTable(['الاسم','الصفة','الرقم الشخصي','بيانات إضافية'],(c.parties||[]).map(p=>[p.name,p.role,p.id,p.extra]));
  $('#detailAssets').innerHTML=`<div class="metric-strip"><div class="metric-box"><span>إجمالي الأصول</span><strong>${money(c.assetsTotal)}</strong></div><div class="metric-box"><span>عدد الأصول</span><strong>${c.assets?.length||0}</strong></div><div class="metric-box"><span>موثقة/مطابقة</span><strong>${(c.assets||[]).filter(a=>['موثق','مطابق'].includes(a.status)).length}</strong></div></div>`+rowsTable(['النوع','الوصف','القيمة','الحالة','المرجع'],(c.assets||[]).map(a=>[a.type,a.description,a.value,a.status,a.reference]),[null,null,v=>money(v)]);
  $('#detailFinance').innerHTML=`<div class="metric-strip"><div class="metric-box"><span>الرصيد/القيمة الحالية</span><strong>${money(c.assetsTotal)}</strong></div><div class="metric-box"><span>إجمالي الإيرادات المسجلة</span><strong>${money((c.finance||[]).filter(f=>f.amount>0).reduce((a,f)=>a+f.amount,0))}</strong></div><div class="metric-box"><span>إجمالي المصروفات</span><strong>${money(Math.abs((c.finance||[]).filter(f=>f.amount<0).reduce((a,f)=>a+f.amount,0)))}</strong></div></div>`+rowsTable(['الحركة','المبلغ','التاريخ'],(c.finance||[]).map(f=>[f.label,f.amount,f.date]),[null,v=>money(v)]);
  $('#detailRequests').innerHTML=`<div class="detail-toolbar"><h3>الطلبات والموافقات</h3><button class="btn btn-primary" id="detailCreateRequest">＋ طلب جديد</button></div>`+rowsTable(['رقم الطلب','النوع','المبلغ','الحالة'],(c.requests||[]).map(r=>[r.id,r.type,r.amount,r.status]),[null,null,v=>v==null?'—':money(v)]);
  $('#detailDocs').innerHTML=rowsTable(['المستند','الحالة'],(c.docs||[]).map(d=>[d.name,d.status]));
  $('#detailAudit').innerHTML=rowsTable(['الإجراء','المستخدم','الوقت','النوع'],(c.audit||[]).slice().reverse().map(a=>[a.action,a.user,a.date,'<span class="audit-tag">سجل تدقيق</span>']),[null,null,null,v=>v]);
  initTabs($('#caseModal'));$('#detailCreateRequest')?.addEventListener('click',()=>openCaseAction('request'));$('#detailAddParty')?.addEventListener('click',()=>toast('في النسخة التالية يمكن ربط إضافة الطرف بنموذج APEX فرعي.'));openModal('caseModal')
}

function initTabs(root=document){$$('.tab-btn',root).forEach(btn=>{if(btn.dataset.bound)return;btn.dataset.bound='1';btn.addEventListener('click',()=>{const group=btn.closest('[data-tabs]');if(!group)return;$$('.tab-btn',group).forEach(x=>x.classList.remove('active'));$$('.tab-panel',group).forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('#'+btn.dataset.tab,group)?.classList.add('active')})})}

const primaryConfig={
 estate:{title:'المعلومات الرئيسية للتركة',hint:'أدخل بيانات المتوفى والمرجع القضائي الأساسي.',fields:[['deceasedName','اسم المتوفى','text',true],['personalId','الرقم الشخصي','text',true],['deathDate','تاريخ الوفاة','date',true],['caseRef','رقم الفريضة / القضية','text',true],['court','المحكمة','text',false],['openingSource','مصدر فتح الملف','select',true,['إحالة قضائية','طلب داخلي','نقل من نظام سابق']]]},
 minor:{title:'المعلومات الرئيسية للقاصر',hint:'أدخل بيانات القاصر ومصدر المال والملف المرتبط إن وجد.',fields:[['minorName','اسم القاصر','text',true],['personalId','الرقم الشخصي','text',true],['birthDate','تاريخ الميلاد','date',true],['fundSource','مصدر المال','select',true,['تركة','هبة','تعويض','دخل/استثمار','أخرى']],['relatedCase','رقم ملف مرتبط (اختياري)','text',false],['openingSource','مصدر فتح الملف','select',true,['إحالة قضائية','نقل من تركة','طلب داخلي']]]},
 interdicted:{title:'المعلومات الرئيسية للمحجور عليه',hint:'أدخل بيانات الشخص وقرار الحجر والمرجع القضائي.',fields:[['personName','اسم المحجور عليه','text',true],['personalId','الرقم الشخصي','text',true],['decisionNo','رقم قرار الحجر','text',true],['decisionDate','تاريخ القرار','date',true],['court','المحكمة','text',true],['openingSource','مصدر فتح الملف','select',true,['إحالة قضائية','نقل من نظام سابق']]]}
};
const partyRoles={estate:['قاصر / وارث','وارث بالغ','ولي','وصي','وكيل','دائن','طرف آخر'],minor:['القاصر','ولي','وصي','وكيل','طرف مرتبط'],interdicted:['المحجور عليه','قيم','وكيل','قريب','طرف مرتبط']};
const documentConfig={estate:[['شهادة الوفاة',true],['الفريضة الشرعية / الحكم',true],['البطاقات الشخصية للورثة',false],['سندات الملكية',false],['كشوف الحسابات البنكية',false]],minor:[['شهادة الميلاد / البطاقة',true],['قرار الولاية أو الوصاية',true],['مستند مصدر المال',true],['كشف حساب',false]],interdicted:[['قرار المحكمة بالحجر',true],['قرار تعيين القيم',true],['البطاقة الشخصية',true],['حصر الأصول',false],['كشوف الحسابات',false]]};
function renderPrimaryFields(){const cfg=primaryConfig[wizardState.type];$('#primaryStepTitle').textContent=cfg.title;$('#primaryStepHint').textContent=cfg.hint;$('#dynamicPrimaryFields').innerHTML=cfg.fields.map(([id,label,type,req,options])=>`<label class="form-field"><span>${label}${req?' *':''}</span>${type==='select'?`<select id="w_${id}" ${req?'required':''}><option value="">اختر...</option>${options.map(o=>`<option>${o}</option>`).join('')}</select>`:`<input id="w_${id}" type="${type}" ${req?'required':''} placeholder="${label}">`}<small class="field-help">${req?'حقل إلزامي':'اختياري'}</small></label>`).join('')}
function renderPartyRoles(){const sel=$('#partyRole');sel.innerHTML=partyRoles[wizardState.type].map(x=>`<option>${x}</option>`).join('');$('#partiesStepTitle').textContent=wizardState.type==='estate'?'الأطراف والورثة':wizardState.type==='minor'?'القاصر والولي/الوصي':'المحجور عليه والقيم والأطراف';$('#partyExtraLabel').textContent=wizardState.type==='estate'?'نسبة الاستحقاق / بيان إضافي':'بيان إضافي'}
function renderDocuments(){const docs=documentConfig[wizardState.type];$('#documentsChecklist').innerHTML=docs.map(([name,req],i)=>`<label class="doc-check"><input type="checkbox" data-doc="${esc(name)}" ${i<2?'checked':''}><div><strong>${esc(name)}</strong><small>${req?'مطلوب عادةً لبدء الملف':'يمكن استكماله لاحقاً'}</small></div>${req?'<span class="required">مطلوب</span>':''}</label>`).join('')}
function updateWizardType(){const checked=$('input[name="caseType"]:checked');wizardState.type=checked?.value||'estate';$$('.case-type-card').forEach(c=>c.classList.toggle('selected',c.querySelector('input').checked));$('#typeHelp').innerHTML=`<strong>${typeMeta[wizardState.type].label}:</strong> ${typeMeta[wizardState.type].help}`;renderPrimaryFields();renderPartyRoles();renderDocuments();$('#wizardTitle').textContent=`فتح ملف ${typeMeta[wizardState.type].label} جديد`}
function renderPartyList(){$('#partyList').innerHTML=wizardState.parties.map((p,i)=>`<div class="record-item"><div class="record-item-main"><span class="record-icon">♙</span><div><strong>${esc(p.name)}</strong><small>${esc(p.role)} • ${esc(p.id||'بدون رقم')} • ${esc(p.extra||'—')}</small></div></div><button type="button" class="remove-record" data-remove-party="${i}">حذف</button></div>`).join('');$$('[data-remove-party]').forEach(b=>b.onclick=()=>{wizardState.parties.splice(Number(b.dataset.removeParty),1);renderPartyList()})}
function renderAssetList(){$('#assetList').innerHTML=wizardState.assets.map((a,i)=>`<div class="record-item"><div class="record-item-main"><span class="record-icon">${a.icon}</span><div><strong>${esc(a.type)} — ${esc(a.description)}</strong><small>${money(a.value)} • ${esc(a.status)} • ${esc(a.reference||'بدون مرجع')}</small></div></div><button type="button" class="remove-record" data-remove-asset="${i}">حذف</button></div>`).join('');$('#wizardAssetTotal').textContent=money(wizardState.assets.reduce((s,a)=>s+Number(a.value||0),0));$$('[data-remove-asset]').forEach(b=>b.onclick=()=>{wizardState.assets.splice(Number(b.dataset.removeAsset),1);renderAssetList()})}
function collectPrimary(){const cfg=primaryConfig[wizardState.type];const obj={};cfg.fields.forEach(([id,label])=>obj[label]=$('#w_'+id)?.value||'—');return obj}
function validateWizardStep(){const panel=$(`.wizard-panel[data-panel="${wizardState.step}"]`);if(wizardState.step===1){let ok=true;$$('[required]',panel).forEach(i=>{i.closest('.form-field')?.classList.remove('invalid');if(!i.value){i.closest('.form-field')?.classList.add('invalid');ok=false}});if(!ok){toast('يرجى استكمال الحقول الإلزامية');return false}}if(wizardState.step===2&&wizardState.parties.length===0){toast('أضف طرفاً واحداً على الأقل للملف');return false}return true}
function renderWizardReview(){const primary=collectPrimary(),docs=$$('#documentsChecklist input:checked').map(i=>i.dataset.doc);const primaryLines=Object.entries(primary).map(([k,v])=>`<div class="review-line"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('');$('#wizardReview').innerHTML=`<div class="review-card"><h4>${typeMeta[wizardState.type].icon} ${typeMeta[wizardState.type].label} — المعلومات الرئيسية</h4>${primaryLines}</div><div class="review-card"><h4>الأطراف (${wizardState.parties.length})</h4><div class="review-list">${wizardState.parties.map(p=>`<div class="review-pill"><strong>${esc(p.name)}</strong> — ${esc(p.role)}</div>`).join('')||'لا يوجد'}</div></div><div class="review-card"><h4>الأصول (${wizardState.assets.length})</h4><div class="review-line"><span>إجمالي القيمة</span><strong>${money(wizardState.assets.reduce((s,a)=>s+Number(a.value||0),0))}</strong></div><div class="review-list">${wizardState.assets.map(a=>`<div class="review-pill">${esc(a.type)} — ${money(a.value)}</div>`).join('')||'<div class="review-pill">لا توجد أصول مضافة حالياً</div>'}</div></div><div class="review-card"><h4>المستندات والتكليف</h4><div class="review-line"><span>الموظف</span><strong>${esc($('#wizardOfficer').value)}</strong></div><div class="review-line"><span>الحالة الأولية</span><strong>${statusMeta[$('#wizardInitialStatus').value].label}</strong></div><div class="review-line"><span>المستندات المتوفرة</span><strong>${docs.length}</strong></div></div>`}
function paintWizard(){const total=6;$$('.wizard-panel').forEach((p,i)=>p.classList.toggle('active',i===wizardState.step));$$('.wizard-step').forEach((s,i)=>{s.classList.toggle('active',i===wizardState.step);s.classList.toggle('done',i<wizardState.step)});$('#wizardPrev').disabled=wizardState.step===0;$('#wizardNext').classList.toggle('hidden',wizardState.step===total-1);$('#wizardCreate').classList.toggle('hidden',wizardState.step!==total-1);$('#stepCounter').textContent=wizardState.step+1;$('#wizardProgressBar').style.width=`${((wizardState.step+1)/total)*100}%`;if(wizardState.step===5)renderWizardReview()}
function resetWizard(){wizardState.step=0;wizardState.type='estate';wizardState.parties=[];wizardState.assets=[];wizardState.assetType=null;$('#caseWizard')?.reset();const first=$('input[name="caseType"][value="estate"]');if(first)first.checked=true;renderPartyList();renderAssetList();$('#assetEditor').classList.add('hidden');updateWizardType();paintWizard()}
function createCaseFromWizard(){const primary=collectPrimary();const cfg=primaryConfig[wizardState.type];const mainNameKey=cfg.fields[0][1];const personalKey=cfg.fields.find(x=>x[0]==='personalId')?.[1];const prefix=typeMeta[wizardState.type].prefix;const year=new Date().getFullYear();const nums=cases.filter(c=>c.id.startsWith(`${prefix}-${year}-`)).map(c=>Number(c.id.split('-').pop())).filter(Boolean);const next=String(Math.max(0,...nums)+1).padStart(5,'0');const id=`${prefix}-${year}-${next}`;const docs=$$('#documentsChecklist input:checked').map(i=>({name:i.dataset.doc,status:'مرفق'}));const assetsTotal=wizardState.assets.reduce((s,a)=>s+Number(a.value||0),0);const c={id,type:wizardState.type,name:wizardState.type==='estate'?`ورثة ${primary[mainNameKey]}`:primary[mainNameKey],subject:primary[mainNameKey],personalId:primary[personalKey],status:$('#wizardInitialStatus').value,officer:$('#wizardOfficer').value,assetsTotal,completion:Math.min(100,55+wizardState.parties.length*8+docs.length*5+Math.min(15,wizardState.assets.length*5)),lastAction:'الآن',opened:new Date().toLocaleDateString('ar-BH'),priority:$('#wizardPriority').value,overdue:false,missing:docs.length<2,reference:Object.values(primary).find(v=>String(v).match(/[A-Z]{2}-|SH-|CV-/))||'—',court:primary['المحكمة']||'—',primary,parties:structuredClone(wizardState.parties),assets:structuredClone(wizardState.assets),docs,finance:assetsTotal?[{label:'رصيد/قيمة افتتاحية',amount:assetsTotal,date:new Date().toLocaleDateString('ar-BH')}]:[],requests:[],audit:[{action:'إنشاء الملف عبر المعالج',user:'نواف محمد',date:nowStamp()}],related:[],notes:$('#wizardNotes').value};cases.unshift(c);saveCases();updateOfficerFilter();calcStats();filters={type:'all',status:'all',officer:'all',q:'',quick:null};renderCases();closeModal('wizardModal');toast(`تم إنشاء الملف ${id} تجريبياً`);setTimeout(()=>showCase(id),300)}
function initWizard(){updateWizardType();paintWizard();$$('input[name="caseType"]').forEach(r=>r.addEventListener('change',updateWizardType));$('#wizardNext').addEventListener('click',()=>{if(validateWizardStep()&&wizardState.step<5){wizardState.step++;paintWizard()}});$('#wizardPrev').addEventListener('click',()=>{if(wizardState.step>0){wizardState.step--;paintWizard()}});$$('.wizard-step').forEach((s,i)=>s.addEventListener('click',()=>{if(i<=wizardState.step||validateWizardStep()){wizardState.step=i;paintWizard()}}));$('#addParty').addEventListener('click',()=>{const name=$('#partyName').value.trim();if(!name)return toast('أدخل اسم الطرف أولاً');wizardState.parties.push({name,role:$('#partyRole').value,id:$('#partyId').value.trim(),extra:$('#partyExtra').value.trim()||'—'});['#partyName','#partyId','#partyExtra'].forEach(s=>$(s).value='');renderPartyList();toast('تمت إضافة الطرف')});$$('[data-asset]').forEach(b=>b.addEventListener('click',()=>{wizardState.assetType={type:b.dataset.asset,icon:b.dataset.icon};$('#assetEditorTitle').textContent=`إضافة ${b.dataset.asset}`;$('#assetDescription').value='';$('#assetValue').value='';$('#assetReference').value='';$('#assetEditor').classList.remove('hidden');$('#assetDescription').focus()}));$('#cancelAsset').onclick=()=>$('#assetEditor').classList.add('hidden');$('#saveAsset').onclick=()=>{const d=$('#assetDescription').value.trim(),v=Number($('#assetValue').value);if(!d)return toast('أدخل وصف الأصل');wizardState.assets.push({type:wizardState.assetType.type,icon:wizardState.assetType.icon,description:d,value:v||0,status:$('#assetStatus').value,reference:$('#assetReference').value.trim()});renderAssetList();$('#assetEditor').classList.add('hidden');toast('تمت إضافة الأصل')};$('#wizardCreate').onclick=createCaseFromWizard;$('#newFileBtn').onclick=()=>{resetWizard();openModal('wizardModal')}}

let pendingAction=null;
function openCaseAction(type){const c=cases.find(x=>x.id===currentCaseId);if(!c)return;pendingAction=type;const body=$('#actionBody'),title=$('#actionTitle');if(type==='status'){title.textContent='تغيير حالة الملف';body.innerHTML=`<div class="action-options">${Object.entries(statusMeta).map(([k,v])=>`<label class="action-option"><input type="radio" name="newStatus" value="${k}" ${k===c.status?'checked':''}><span>${v.label}</span></label>`).join('')}</div>`}else if(type==='assign'){title.textContent='تغيير الموظف المختص';body.innerHTML=`<label class="form-field"><span>الموظف الجديد</span><select id="newOfficer">${officers.map(o=>`<option ${o===c.officer?'selected':''}>${o}</option>`).join('')}</select></label>`}else if(type==='request'){title.textContent='إنشاء طلب جديد';body.innerHTML=`<div class="form-stack"><label class="form-field"><span>نوع الطلب</span><select id="requestType"><option>طلب صرف</option><option>بيع / تصرف في أصل</option><option>صيانة عقار</option><option>تحديث بيانات طرف</option><option>طلب آخر</option></select></label><label class="form-field"><span>المبلغ (إن وجد)</span><input id="requestAmount" type="number" min="0" step="0.001"></label><label class="form-field"><span>الملاحظات</span><textarea id="requestNote"></textarea></label></div>`}else{title.textContent='إضافة إجراء / ملاحظة';body.innerHTML=`<label class="form-field"><span>وصف الإجراء</span><textarea id="actionNote" placeholder="اكتب الإجراء أو الملاحظة الداخلية..."></textarea></label>`}openModal('actionModal')}
function confirmCaseAction(){const c=cases.find(x=>x.id===currentCaseId);if(!c)return;if(pendingAction==='status'){const v=$('input[name="newStatus"]:checked')?.value;c.status=v;c.audit.push({action:`تغيير حالة الملف إلى ${statusMeta[v].label}`,user:'نواف محمد',date:nowStamp()})}else if(pendingAction==='assign'){const v=$('#newOfficer').value;c.officer=v;c.audit.push({action:`إعادة تكليف الملف إلى ${v}`,user:'نواف محمد',date:nowStamp()})}else if(pendingAction==='request'){const type=$('#requestType').value,amount=Number($('#requestAmount').value)||null;const id=`RQ-${new Date().getFullYear()}-${String(Math.floor(Math.random()*900)+100)}`;c.requests=c.requests||[];c.requests.unshift({id,type,amount,status:'قيد المراجعة'});c.audit.push({action:`إنشاء ${type} — ${id}`,user:'نواف محمد',date:nowStamp()})}else{const note=$('#actionNote').value.trim();if(!note)return toast('اكتب وصف الإجراء');c.audit.push({action:note,user:'نواف محمد',date:nowStamp()})}c.lastAction='الآن';saveCases();calcStats();renderCases();closeModal('actionModal');showCase(c.id);toast('تم حفظ الإجراء التجريبي')}

function initShell(){loadCases();updateOfficerFilter();calcStats();renderCases();const sidebar=$('#sidebar'),main=$('#main');$('#workingDate').textContent=new Date().toLocaleDateString('ar-BH',{weekday:'long',year:'numeric',month:'long',day:'numeric'});$('#navToggle').onclick=()=>{if(innerWidth<=820)sidebar.classList.toggle('mobile-open');else{sidebar.classList.toggle('collapsed');main.classList.toggle('expanded')}};$$('.nav-parent').forEach(b=>b.onclick=()=>b.closest('.nav-group').classList.toggle('open'));$$('.nav-item[data-view]').forEach(i=>i.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));i.classList.add('active');$('#currentCrumb').textContent=i.dataset.title;applyView(i.dataset.view,i.dataset.title);if(innerWidth<=820)sidebar.classList.remove('mobile-open')});
  $$('#typeChips .chip').forEach(b=>b.onclick=()=>{filters.type=b.dataset.type;filters.quick=null;updateFiltersUI();renderCases()});$('#statusFilter').onchange=e=>{filters.status=e.target.value;filters.quick=null;renderCases()};$('#officerFilter').onchange=e=>{filters.officer=e.target.value;renderCases()};$('#searchInput').oninput=e=>{filters.q=e.target.value;renderCases()};$('#clearFilters').onclick=()=>{filters={type:'all',status:'all',officer:'all',q:'',quick:null};updateFiltersUI();renderCases()};
  $$('.kpi-card[data-status-filter]').forEach(k=>k.onclick=()=>{filters.status=k.dataset.statusFilter;filters.quick=null;updateFiltersUI();renderCases();$('#filesRegion').scrollIntoView({behavior:'smooth'})});$$('[data-quick-filter]').forEach(b=>b.onclick=()=>{filters.quick=b.dataset.quickFilter;filters.type='all';filters.status='all';updateFiltersUI();renderCases();$('#filesRegion').scrollIntoView({behavior:'smooth'})});$('[data-view-jump="all"]').onclick=()=>applyView('all','جميع الملفات');
  $('#globalSearch').oninput=e=>{filters.q=e.target.value;$('#searchInput').value=e.target.value;renderCases()};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus()}if(e.key==='Escape'){$$('.modal-shell.open').forEach(m=>closeModal(m.id));closeDrawer()}});
  $('#exportBtn').onclick=()=>toast('تم تجهيز تصدير تجريبي. في APEX يمكن ربطه بـ Interactive Report Download.');$('#notificationsBtn').onclick=openDrawer;$('[data-drawer-close]').onclick=closeDrawer;$('#drawerBackdrop').onclick=closeDrawer;$('#markNotifications').onclick=()=>{$$('.notification-item').forEach(n=>n.classList.remove('unread'));$('#notificationCount').textContent='0';toast('تم تحديد التنبيهات كمقروءة')};
  $$('.modal-close').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));$$('.modal-shell').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));$('#caseAddAction').onclick=()=>openCaseAction('note');$('#caseCreateRequest').onclick=()=>openCaseAction('request');$('#caseChangeStatus').onclick=()=>openCaseAction('status');$('#caseAssign').onclick=()=>openCaseAction('assign');$('#casePrint').onclick=()=>window.print();$('#actionConfirm').onclick=confirmCaseAction;initWizard()}
function openDrawer(){$('#notificationDrawer').classList.add('open');$('#notificationDrawer').setAttribute('aria-hidden','false');$('#drawerBackdrop').classList.add('show')}
function closeDrawer(){$('#notificationDrawer').classList.remove('open');$('#notificationDrawer').setAttribute('aria-hidden','true');$('#drawerBackdrop').classList.remove('show')}
function initLogin(){$('#ekeyBtn')?.addEventListener('click',()=>{toast('محاكاة نجاح التحقق عبر eKey');setTimeout(()=>location.href='index.html',650)});$('#staffLogin')?.addEventListener('submit',e=>{e.preventDefault();if(!$('#username').value.trim()||!$('#password').value.trim())return toast('يرجى إدخال اسم المستخدم وكلمة المرور');toast('تم تسجيل الدخول التجريبي');setTimeout(()=>location.href='index.html',600)})}
document.addEventListener('DOMContentLoaded',()=>{if($('#sidebar'))initShell();initLogin()});
